[package]
name = "kaif-browser"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tauri = { version = "2", features = [] }
tauri-build = "2"

[build-dependencies]
tauri-build = "2"

[patch.crates-io]
alloc-no-stdlib = { git = "https://github.com/dropbox/rust-alloc-no-stdlib", branch = "master" }
brotli = { git = "https://github.com/dropbox/rust-brotli", branch = "master" }
