[package]
name = "kaif-browser"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "kaif_browser_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "kaif-browser"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"

[patch.crates-io]
alloc-no-stdlib = { git = "https://github.com/dropbox/rust-alloc-no-stdlib", branch = "master" }
brotli = { git = "https://github.com/dropbox/rust-brotli", branch = "master" }